image: registry.spring25a.secoder.net/tool/deployer

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: 
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build
  only:
    - main
    - dev

.test:
  image: node:22
  stage: test

  before_script:
    - corepack enable
    - pnpm config set registry https://registry.npmmirror.com
    - pnpm install

unit-test:
  extends: .test
  script:
    - pnpm test --coverage
  after_script:
    - SUFFIX=$RANDOM
    - curl "http://api.spring25a.secoder.net/static/sonar-scanner.tar.gz" -s -o "/tmp/sonar-$SUFFIX.tar.gz"
    - tar -xf "/tmp/sonar-$SUFFIX.tar.gz" -C /opt
    - sed -i 's/sonarqube.secoder.net/sonarqube.spring25a.secoder.net/g' /opt/sonar-scanner/conf/sonar-scanner.properties
    - sed -i 's/api.secoder.net/api.spring25a.secoder.net/g' /opt/sonar-scanner/bin/sonar-scanner
    - /opt/sonar-scanner/bin/sonar-scanner
      -Dsonar.testExecutionReportPaths=reports/junit.xml
      -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
  artifacts:
    paths:
      - reports/
      - coverage/
  allow_failure: true

style-test:
  extends: .test
  script:
    - pnpm lint
  allow_failure: true


deploy:
  stage: deploy
  script:
    - export API_SERVER=https://deployer.spring25a.secoder.net/api
    - deployer dyno replace frontend $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG gitlab-ci-token $REGISTRY_PWD
  only:
    - main
    - dev